### ISSUE TITLE
BUG: Sort by "recently updated" is not working

### ISSUE THREAD

**Issue by tmori3y2** [gitbucket/gitbucket#1655] opened 2017-07-24 15:50 UTC
## Issue
**Impacted version**: 4.13.0

**Deployment mode**:  using gitBucket which is hosted on a server of a university which is a collaborative research partner via a proxy of my company

**Problem description**:
- Go to "issue"
- Select to sort by "Recently updated"
- All updates by other users are ignored.

In GitHub or GitLab, the update date and time are displayed under the title of the problem and sorted in that order. Of course, all updates, including updates by other users, will be reflected in the sort result.

**Comment by tmori3y2** [comment] 2017-07-24 16:03
#1651

The history that I edited the title of the issue is not recorded in the issue, but it is reflected in the sort result.

The history of all operations related to the issue should be recorded, and operations that do not record the history should not be reflected in the sorting result, I think.

**Comment by takezoe** [comment] 2017-07-24 16:41
Certainly the current behavior isn't useful, but since it's intended behavior it's not a bug.

> The history of all operations related to the issue should be recorded, and operations that do not record the history should not be reflected in the sorting result, I think.

I don't think so because GitBucket doesn't record editing history. But agree with that all editing should be reflected to the updated date of the issue.

**Comment by takezoe** [comment] 2017-08-05 18:39
Fixed in 8ab96f09cbaa789bd463868b191dbc74e8119691.

**Closed by takezoe** 2017-08-05 18:39 UTC
