### ISSUE TITLE
Milestone rendering is broken in issue/PR page

### ISSUE THREAD

**Issue by SIkebe** [gitbucket/gitbucket#2429] opened 2020-02-16 06:43 UTC
## Issue
**Impacted version**: 4.33.0

**Deployment mode**: standalone app

**Problem description**:
Milestone is rendered correctly when you set for the first time, but it's broken when you reload the page.
![image](https://user-images.githubusercontent.com/17608272/74600274-49d0db00-50d2-11ea-9c02-b95c5a75428f.png)

**Comment by joobisb** [comment] 2020-02-27 09:57
@SIkebe could you please elaborate on the steps to reproduce this..cause i cannot reproduce it

**Comment by SIkebe** [comment] 2020-02-27 10:56
@joobisb Hmm... nothing special. Just `java -jar gitbucket.war`, create a milestone and set it to an issue.
* Windows 10 1909
* AdoptOpenJDK 1.8.0_242
* Chrome 80
![image](https://user-images.githubusercontent.com/17608272/75438334-18da8b00-599b-11ea-8fe6-c93d124ef854.png)

**Comment by SIkebe** [comment] 2020-02-27 11:35
Seems to be fixed by this
![image](https://user-images.githubusercontent.com/17608272/75441100-61487780-59a0-11ea-88c0-3b36d7138e5e.png)

@takezoe You changed these lines in 71248cd9b7b0868d32af2d2fb04119d115346830. Any thoughts? Related to the twirl update?

**Comment by kasancode** [comment] 2020-02-27 13:06
I have same problems on
- Windows 10 1909 + Java 10.0 + GB 4.33
- Debian Linux 8 + OpenJDK 1.8 + GB 4.33

Also, #2423 contains similar fix.
https://github.com/gitbucket/gitbucket/pull/2423/files#diff-5258892efdacd3193b5b6093b4661255

Sorry, I should have notified properly information before.

**Comment by takezoe** [comment] 2020-03-31 17:04
Hmm... I can't reproduce this issue with Chrone and Firefix on Mac.

**Comment by SIkebe** [comment] 2020-08-17 16:31
Reproduced the same issue with current `master` running on Ubuntu 20.0.4 (WSL2).

**Comment by takezoe** [comment] 2021-02-20 23:01
Sorry, I could reproduce this and made a fix. Maybe I should have tried clean compile to reproduce this.

If I remember correctly, 71248cd9b7b0868d32af2d2fb04119d115346830 was introduced to avoid [a Twirl bug](https://github.com/playframework/twirl/issues/232) in 1.4.1 and it seems to has been [fixed in 1.5.0](https://github.com/playframework/twirl/pull/233).

**Closed** 2021-02-20 23:06 UTC
Labels: bug
