### ISSUE TITLE
can't delete files and directories

### ISSUE THREAD

**Issue by RHS-Code** [gitbucket/gitbucket#2312] opened 2019-05-03 05:58 UTC
## Issue
**Impacted version**: 4.31.2

**Deployment mode**: *explain here how you use GitBucket : standalone app (java)
**Problem description**:
I've tried to remove some unnecessary files and directories using `git rm some file && 
git commit -m "deleted files" &&
git push -u origin master`
but the files are still visible on the GitBucket interface. Did I make a mistake, is it a bug or just a misunderstood feature of git/GitBucket?

**Comment by takezoe** [comment] 2019-05-04 00:29
I can't reproduce your situation. I tried your procedure but files were removed properly.

**Comment by takezoe** [comment] 2022-04-17 08:45
Closing old questions.

**Closed by takezoe** 2022-04-17 08:45 UTC
Labels: question
