### ISSUE TITLE
Gitbucket 4.11 is invalidate SSH-Keys which contains newline character

### ISSUE THREAD

**Issue by amuramatsu** [gitbucket/gitbucket#1523] opened 2017-04-03 14:56 UTC
## Issue
**Impacted version**: 4.11

**Deployment mode**: standalone app

**Problem description**:

Gitbucket 4.10 or before allow newline charactor at SSH-Key strings. When I update Gitbucket from 4.10 to 4.11, all SSH-keys with newlines stored database become invalid-keys.

**Comment by ritschwumm** [comment] 2017-04-03 15:32
this https://github.com/gitbucket/gitbucket/commit/f4da49b5bd2a80fd1351930541265d0f5f8d1382#diff-291fa2451651f1a02e84f9874f86fc26L25 looks like it could be the cause

**Comment by takezoe** [comment] 2017-04-03 15:35
I can't reproduce in my environment. Public key with newline works fine.

**Comment by takezoe** [comment] 2017-04-03 15:35
@ritschwumm Are you getting a same trouble?

**Comment by kounoike** [comment] 2017-04-03 16:03
I can reproduce it.
When some newline insert into rsa-key, 4.11 says invalid key. 4.10 accepts.

**Comment by ritschwumm** [comment] 2017-04-03 16:24
@takezoe i have not tried it, but having done some changes on the ssh code i thought i'd grab the opportunity to see what has changes since then and skim over the relevant commits.

**Comment by takezoe** [comment] 2017-04-03 21:49
@amuramatsu @kounoike Hmm... I need more information.
- Is "invalid-keys" shown in public key registration? In both the account settings and the deploy keys settings?
- client operating system and browser (Let me know the result of trying with Google Chrome if it's possible)

**Comment by takezoe** [comment] 2017-04-03 21:53
@ritschwumm I see. Thanks.

**Comment by kounoike** [comment] 2017-04-03 22:20
> Is "invalid-keys" shown in public key registration? In both the account settings and the deploy keys settings?

both.
In account settings, `/:user/_ssh/validate` returns `{"publicKey":"Key is invalid."}`.
In deploy keys, server accpets keys, but it shows `(Key is invalid.)`

> client operating system and browser (Let me know the result of trying with Google Chrome if it's possible)

Windows/Chrome.
Hmm... CR+LF? I read HTTP transaction by Fiddler, client sends `publickKey=....%0D%0A....`
But, I think it is correct for MIME encoding.

**Comment by amuramatsu** [comment] 2017-04-03 23:20
>@amuramatsu @kounoike Hmm... I need more information.
>
>* Is "invalid-keys" shown in public key registration? In both the account settings and the deploy keys settings?
>* client operating system and browser (Let me know the result of trying with Google Chrome if it's possible)

* "invalid-keys" is shown in account settings' registration.  Deploy keys settings is not tested yet.
* Client OS: Window 7 32bit/64bit, Browser: Firefox 52.0.2 32bit/64bit
  Chrome is not installed test machines, but I can install and test them.

**Comment by takezoe** [comment] 2017-04-04 16:14
@amuramatsu I got how to reproduce this issue from @kounoike. That was inserting newline in the middle of the public key. Is this same as your situation?

**Comment by amuramatsu** [comment] 2017-04-05 13:08
>@amuramatsu I got how to reproduce this issue from @kounoike. That was inserting newline in the >middle of the public key. Is this same as your situation?

Yes, It's same. I used ssh-keys such as `ssh-rsa AAAAB3...\nE5PYk...w==` at gitbucket 4.10, but it's invalidate at 4.11.

**Comment by takezoe** [comment] 2017-04-05 16:39
@amuramatsu Thanks! I fixed in 68c2f83. It will be released in 4.12.

**Closed by takezoe** 2017-04-05 16:39 UTC
Labels: bug

**Comment by ritschwumm** [comment] 2017-04-05 17:29
do you need to re-add your key with this fix in place?

**Comment by webard** [comment] 2017-05-23 07:59
Still the same bug in 4.12.1

**Comment by bdgscotland** [comment] 2017-07-20 06:31
I'm having the same trouble even with 4.14.1

**Comment by takezoe** [comment] 2017-07-21 01:42
@bdgscotland Have you tried to re-add your keys?

**Comment by holgerdell** [comment] 2017-12-22 12:08
I'm getting "Key is invalid" on gitbucket 4.19.3
