### ISSUE TITLE
Can't view changes made in java files on the Commit page

### ISSUE THREAD

**Issue by kingdevnl** [gitbucket/gitbucket#1735] opened 2017-10-11 09:37 UTC
It shows Not supported, Any idea why
(As far as i remeber it always worked i could be wrong on this)

**Comment by takezoe** [comment] 2017-10-11 09:47
Maybe duplicate of #1727 and already fixed. Please wait for the next release.

**Comment by kingdevnl** [comment] 2017-10-11 09:48
Thanks.

**Closed by takezoe** 2017-10-11 09:47 UTC
Labels: duplicate
