### ISSUE TITLE
Multiple email addresses for single user.

### ISSUE THREAD

**Issue by michael-rhoese** [gitbucket/gitbucket#1766] opened 2017-11-01 09:13 UTC
First, I have to say thx for this great git server project! I use it for all my projects and it works really good.
Now my question: some time, I push code changes from different workstations and some time I forget to change the commiter mail address. Is it possible to add the functionality to bind multiple email addresses to one user? This can help to bind events to one user (like bitbucket).

Regard Micha

**Comment by aadrian** [comment] 2017-11-01 12:22
@michael-rhoese duplicate of #652

**Closed by aadrian** 2017-11-01 12:22 UTC
