### ISSUE TITLE
branch protection not workd on reverse proxy with prefix

### ISSUE THREAD

**Issue by niblings** [gitbucket/gitbucket#1131] opened 2016-03-01 07:40 UTC
**Impacted version**: 3.11 or 3.12
**Deployment mode**: standalone with apache or tomcat7 with apache (ajp or http)

standalone
```
--prefix=/gitbucket
```

apache
```
<Location /gitbucket>
  ProxyPass http://localhost:8080/gitbucket
  ProxyPassReverse http://localhost:8080/gitbucket
</Location>
```

**Problem description**:
ajax 'update error'
path prefix replacement?
ajp13 or tomcat7 PATCH not supported?

https://github.com/gitbucket/gitbucket/blob/master/src/main/twirl/gitbucket/core/settings/branchprotection.scala.html#L110
```
$.ajax({
    method:'PATCH',
    url:'/api/v3/repos/@repository.owner/@repository.name/branches/@encodeRefName(branch)',
```

**Comment by niblings** [comment] 2016-03-01 16:56
![image](https://cloud.githubusercontent.com/assets/12636866/13434407/15d36e4a-e019-11e5-9134-988aecd36c0f.png)

firefox (44.0.2) screenshot.

httpd access_log
```
192.168.xxx.xxx - - [02/Mar/2016:01:53:10 +0900] "PATCH /api/v3/repos/[group]/[repository]/branches/master HTTP/1.1" 405 270

```

**Comment by niblings** [comment] 2016-03-01 19:31
It was possible to request api
running on standalone gitbucket with prefix=gitbucket and apache reverse proxy
```
curl -v -H "Cookie: JSESSIONID=[sessionid]" -H "Accept: application/json" -H "Content-type: application/json" -X PATCH -d '{"protection":{"enabled":true,"required_status_checks":{"enforcement_level":"off","contexts":[]}}}' 'http://[server]/gitbucket/api/v3/repos/[group]/[repository]/branches/[branch]'
```

httpd access_log (200 OK)
```
192.168.xxx.xxx - - [02/Mar/2016:04:15:35 +0900] "PATCH /gitbucket/api/v3/repos/[group]/[repository]/branches/[branch] HTTP/1.1" 200 171
```
However, it took more than one minute until the completion of the http response.

**Comment by takezoe** [comment] 2016-03-05 01:46
@nazoking This problem is being caused by servlet routing. So it can be resolved by changing order of controllers in [ScalatraBootstrap](https://github.com/gitbucket/gitbucket/blob/master/src/main/scala/ScalatraBootstrap.scala) as:

```scala
    context.mount(new IndexController, "/")
    context.mount(new FileUploadController, "/upload")
    context.mount(new RepositorySettingsController, "/*") // moved from the last
    context.mount(new DashboardController, "/*")
    context.mount(new UserManagementController, "/*")
    context.mount(new SystemSettingsController, "/*")
    context.mount(new AccountController, "/*")
    context.mount(new RepositoryViewerController, "/*")
    context.mount(new WikiController, "/*")
    context.mount(new LabelsController, "/*")
    context.mount(new MilestonesController, "/*")
    context.mount(new IssuesController, "/*")
    context.mount(new PullRequestsController, "/*")
//    context.mount(new RepositorySettingsController, "/*")
```
However, this is not an essential solution. I will try to solve this problem in other way.

**Comment by nazoking** [comment] 2016-03-08 09:59
@takezoe thank you. I assined me beause I thinked that this is javascript bug ..

**Closed** 2016-03-09 16:34 UTC
