### ISSUE TITLE
4.2: Database migration seems to fail for non-empty database - Column "X21.ALLOW_WIKI_EDITING" not found

### ISSUE THREAD

**Issue by uli-heller** [gitbucket/gitbucket#1227] opened 2016-07-02 07:00 UTC
I've upgraded from 4.1 to 4.2 and now I'm getting [this error](https://github.com/gitbucket/gitbucket/files/344439/complete.txt):

```
org.h2.jdbc.JdbcSQLException: Column "X21.ALLOW_WIKI_EDITING" not found; SQL statement:
CREATE FORCE VIEW PUBLIC._1 AS
SELECT
    X21.UPDATED_DATE AS X22,
    X21.ALLOW_WIKI_EDITING AS X23,
    X21.EXTERNAL_ISSUES_URL AS X24,
    X21.PARENT_REPOSITORY_NAME AS X25,
    X21.EXTERNAL_WIKI_URL AS X26,
    X21.DEFAULT_BRANCH AS X27,
    X21.DESCRIPTION AS X28,
    X21.ORIGIN_REPOSITORY_NAME AS X29,
    X21.ORIGIN_USER_NAME AS X30,
    X21.PARENT_USER_NAME AS X31,
    X21.PRIVATE AS X32,
    X21.REPOSITORY_NAME AS X33,
    X21.USER_NAME AS X34,
    X21.ENABLE_WIKI AS X35,
    X21.ENABLE_ISSUES AS X36,
    X21.REGISTERED_DATE AS X37,
    X21.LAST_ACTIVITY_DATE AS X38
FROM PUBLIC.REPOSITORY X21 [42122-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.expression.Alias.optimize(Alias.java:51)
	at org.h2.command.dml.Select.prepare(Select.java:852)
...
```

I've double-checked  using empty databases, i.e.:

```
rm -rf ~/.gitbucket
git checkout 4.1
./sbt.sh package
./sbt.sh executable
java -jar target/executable/gitbucket.war
./sbt.sh clean; rm -rf target; git clean -f
git checkout 4.2
./sbt.sh package
./sbt.sh executable
 java -jar target/executable/gitbucket.war
```

For these, it works without an issue. So the migration seems to fail only when the database actually contains data.

**Comment by uli-heller** [comment] 2016-07-02 08:11
I've found a work around:

```
alter table repository add column allow_wiki_editing boolean;
update repository set allow_wiki_editing=true;
alter table repository alter column allow_wiki_editing boolean not null;
```

Now there is an error related to "EXTERNAL_ISSUES_URL".

**Comment by uli-heller** [comment] 2016-07-02 08:19
Here is the complete work-around. With this, I'm able to login:

1. Try to open a browser using the usual gitbucket url
2. See the error above
3. Connect to the h2 console - append `/console/login.jsp` to the url
4. Login to the h2 database
5. Execute the commands mentioned at the end of this comment
6. Try to open a browser using the usual gitbucket url again
7. No error this time.

Here the commands for the h2 console:

```
alter table repository add column allow_wiki_editing boolean;
update repository set allow_wiki_editing=true;
alter table repository alter column allow_wiki_editing boolean not null;

alter table repository add column external_issues_url varchar(200);
alter table repository add column external_wiki_url varchar(200);

alter table repository add column enable_wiki boolean;
update repository set enable_wiki=true;
alter table repository alter column enable_wiki boolean not null;

alter table repository add column enable_issues boolean;
update repository set enable_issues=true;
alter table repository alter column enable_issues boolean not null;
```

**Comment by takezoe** [comment] 2016-07-02 10:40
@uli-heller Could you show records prior migration in `VERSIONS` table?

If you have troubles the cause is not clear or questions, please send them gitter before raising new issue:
https://gitter.im/gitbucket/gitbucket

**Comment by st0rmchild** [comment] 2016-07-02 11:13
I have the same problem. To answer the question:
* Version before 4.1
* Version displayed before: 4.1.0 after: 4.2.0
* logs:
```
13:09:54.148 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
13:09:54.334 [main] INFO  g.core.servlet.InitializeListener - Start schema update
13:09:54.659 [main] INFO  g.core.servlet.InitializeListener - Initialize plugins
13:09:54.929 [main] INFO  o.quartz.core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
13:09:54.930 [main] INFO  org.quartz.core.QuartzScheduler - Quartz Scheduler v.2.2.1 created.
13:09:54.931 [main] INFO  org.quartz.simpl.RAMJobStore - RAMJobStore initialized.
13:09:54.932 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v2.2.1) 'QuartzScheduler~job' with instanceId 'job'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 1 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

13:09:54.932 [main] INFO  o.quartz.impl.DirectSchedulerFactory - Quartz scheduler 'QuartzScheduler~job
13:09:54.932 [main] INFO  o.quartz.impl.DirectSchedulerFactory - Quartz scheduler version: 2.2.1
13:09:54.933 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler QuartzScheduler~job_$_job started.
[INFO] [07/02/2016 13:09:54.936] [main] [[QuartzScheduler~job]] Setting up scheduled job 'Daily', with 'com.typesafe.akka.extension.quartz.QuartzCronSchedule@15dd5ac2'
13:09:54.943 [main] INFO  o.scalatra.servlet.ScalatraListener - The cycle class name from the config: ScalatraBootstrap
13:09:54.944 [main] INFO  o.scalatra.servlet.ScalatraListener - Initializing life cycle class: ScalatraBootstrap
13:09:55.205 [main] INFO  o.a.sshd.common.util.SecurityUtils - Trying to register BouncyCastle as a JCE provider
13:09:55.346 [main] INFO  o.a.sshd.common.util.SecurityUtils - Registration succeeded
13:09:55.362 [main] INFO  gitbucket.core.ssh.SshServer$ - Start SSH Server Listen on 2220
```

Additional Information:
Runnung on Archlinux:
```Linux ruatha 4.6.3-1-ARCH #1 SMP PREEMPT Fri Jun 24 21:19:13 CEST 2016 x86_64 GNU/Linux```


Using java:
```
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
```

Database overview:
![database](https://cloud.githubusercontent.com/assets/12675567/16540061/ab613e5e-4056-11e6-88bb-44b82ad30f5b.jpg)

**Comment by takezoe** [comment] 2016-07-02 11:55
@st0rmchild If migration isn't successful, version number isn't updated to 4.2. Have you ever used development version?
And it seems that you are showing `~/test` by H2 console but it isn't GitBucket database. To connect GitBucket database, see: https://github.com/gitbucket/gitbucket/wiki/Connect-to-H2-database

**Comment by takezoe** [comment] 2016-07-02 12:01
@st0rmchild You can retry migration to 4.2 by updating a `gitbucket-core` record in the `VERSIONS` table with `4.1` and restarting GitBucket. But it will be fail if you have already migrated manually by the way which is explained by @uli-heller.

**Comment by myururdurmaz** [comment] 2016-07-02 12:03
looks same problem on my server

![screenshot_2016-07-02_15-02-27](https://cloud.githubusercontent.com/assets/1057861/16540250/2262fe7a-4066-11e6-9188-114a640eb181.png)

**Comment by takezoe** [comment] 2016-07-02 12:19
@myururdurmaz Is your update from 4.0 to 4.2? Could find any error in stdout or catalina.out during  boot of GitBucket 4.2?

**Comment by myururdurmaz** [comment] 2016-07-02 12:53
my upgrade 4.1 to 4.2

my log
```
dhc-user@gitbucket:~$ jdk8/bin/java -Xms400M -Xmx1g -jar gitbucket-4.2.war                                                                                   
2016-07-02 13:00:04.297:INFO::main: Logging initialized @583ms
2016-07-02 13:00:04.636:INFO:oejs.Server:main: jetty-9.3.z-SNAPSHOT
2016-07-02 13:00:06.615:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/dhc-user/.gitbucket/tmp/webapp/WEB-INF/lib/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/dhc-user/.gitbucket/tmp/webapp/WEB-INF/lib/slf4j-jdk14-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
13:00:07.516 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
13:00:08.139 [main] INFO  g.core.servlet.InitializeListener - Start schema update
13:00:09.535 [main] INFO  g.core.servlet.InitializeListener - Initialize plugins
13:00:09.637 [main] ERROR gitbucket.core.plugin.PluginRegistry - Error during plugin initialization
java.lang.IncompatibleClassChangeError: Implementing class
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at gitbucket.core.plugin.PluginRegistry$.gitbucket$core$plugin$PluginRegistry$$$anonfun$6(PluginRegistory.scala:189)
        at gitbucket.core.plugin.PluginRegistry$.gitbucket$core$plugin$PluginRegistry$$$anonfun$6$adapted(PluginRegistory.scala:186)
        at gitbucket.core.plugin.PluginRegistry$$$Lambda$13/143486875.apply(Unknown Source)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistory.scala:186)
        at gitbucket.core.servlet.InitializeListener.gitbucket$core$servlet$InitializeListener$$$anonfun$1(InitializeListener.scala:82)
        at gitbucket.core.servlet.InitializeListener.gitbucket$core$servlet$InitializeListener$$$anonfun$1$adapted(InitializeListener.scala:36)
        at gitbucket.core.servlet.InitializeListener$$Lambda$4/1489933928.apply(Unknown Source)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.apply(DatabaseComponent.scala:54)
        at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:426)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
        at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:54)
        at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withTransaction(JdbcBackend.scala:46)
        at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:36)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:837)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:533)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:810)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:345)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1404)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1366)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:411)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:378)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at JettyLauncher.main(JettyLauncher.java:63)
-- Gist plug-in initialized --
13:00:10.443 [main] INFO  o.quartz.core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
13:00:10.446 [main] INFO  org.quartz.core.QuartzScheduler - Quartz Scheduler v.2.2.1 created.
13:00:10.454 [main] INFO  org.quartz.simpl.RAMJobStore - RAMJobStore initialized.
13:00:10.455 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v2.2.1) 'QuartzScheduler~job' with instanceId 'job'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 1 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

13:00:10.457 [main] INFO  o.quartz.impl.DirectSchedulerFactory - Quartz scheduler 'QuartzScheduler~job
13:00:10.457 [main] INFO  o.quartz.impl.DirectSchedulerFactory - Quartz scheduler version: 2.2.1
13:00:10.458 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler QuartzScheduler~job_$_job started.
[INFO] [07/02/2016 13:00:10.474] [main] [[QuartzScheduler~job]] Setting up scheduled job 'Daily', with 'com.typesafe.akka.extension.quartz.QuartzCronSchedule
@5411dd90'
13:00:10.519 [main] INFO  o.scalatra.servlet.ScalatraListener - The cycle class name from the config: ScalatraBootstrap
13:00:10.522 [main] INFO  o.scalatra.servlet.ScalatraListener - Initializing life cycle class: ScalatraBootstrap
13:00:11.741 [main] INFO  o.a.sshd.common.util.SecurityUtils - Trying to register BouncyCastle as a JCE provider
13:00:12.290 [main] INFO  o.a.sshd.common.util.SecurityUtils - Registration succeeded
13:00:12.344 [main] INFO  gitbucket.core.ssh.SshServer$ - Start SSH Server Listen on -----
2016-07-02 13:00:12.521:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@2ff498b0{/,file:///home/dhc-user/.gitbucket/tmp/webapp/,AVAILABLE}{file
:/home/dhc-user/gitbucket-4.2.war}
2016-07-02 13:00:12.529:INFO:oejs.AbstractConnector:main: Started ServerConnector@4cbebc60{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2016-07-02 13:00:12.530:INFO:oejs.Server:main: Started @8853ms


```

**Comment by st0rmchild** [comment] 2016-07-02 12:57
Changing the `gitbucket-core` didn't help. 
Same problem as before
```
SELECT * FROM VERSIONS;
MODULE_ID  	VERSION  
network	1.0
gitbucket-core	4.1
(2 rows, 2 ms)
```

**Comment by takezoe** [comment] 2016-07-02 15:23
@myururdurmaz OK. Update `gitbucket-core` as `4.0.0` and try to run GitBucket 4.2 again.

**Comment by takezoe** [comment] 2016-07-02 15:32
Finally, this is a bug in migration from 3.14 to 4.0.0. I will fix this bug in 4.3.0 and add code to rescue users who updated from 3.14 to 4.0 and be still using 4.0 or 4.1.

**Comment by st0rmchild** [comment] 2016-07-02 15:41
Ok, 
with ```gitbucket-core``` set to to ```4.0.0``` it worked for me. 

Thank you.

**Comment by takezoe** [comment] 2016-07-02 16:11
Fixed in 4.2.1:
https://github.com/gitbucket/gitbucket/releases/tag/4.2.1

**Closed** 2016-07-02 16:11 UTC
Labels: bug

**Comment by uli-heller** [comment] 2016-07-04 05:10
Thanks!

**Comment by codeling** [comment] 2016-08-16 08:46
Just tried upgrading from 4.0.0 to 4.3 and also got this error.
The workaround from [this comment](https://github.com/gitbucket/gitbucket/issues/1227#issuecomment-230090485) worked for me.

**Comment by imeszaros** [comment] 2016-08-16 10:42
The same thing happened to me that @codeling  mentioned when upgrading from 4.1 directly to 4.3, but restarting GitBucket multiple times solved me the problem automatically. My VERSIONS table reports 4.3.0, and everything works fine, except the searchbox at the top. If try to search anything, the page loads forever.. although this might not be related to this problem.
