### ISSUE TITLE
AnyAdministrator can controll Any Private Repository.( like #644 )

### ISSUE THREAD

**Issue by my-dev** [gitbucket/gitbucket#685] opened 2015-03-30 09:32 UTC
Hi! Mr.takezoe.

like #644. but this problem is alive.

If you are [ Administrator ], you can do clone,push,pull any private repository.
even though, other user's repository...

I think, this is a bug. don't you.

##### In Function [ hasWritePermission ]
\------------------------------------------
case Some(a) if(a.isAdmin) => true
\------------------------------------------
I think, above code is no necessary.

**Comment by mgeorge** [comment] 2015-03-30 10:02
I disagree.  Administrators should be able to see and work on all 
repositories in that GitBucket instance.  It is the whole point of being 
an administrator.

My use case - I am an instructor who uses administrator privileges to 
access all of my students' repositories.

Cheers,
Mark

**Comment by nazoking** [comment] 2015-03-30 10:14
I think this is not a bug, but this change is good. in now, administrator is too much powerful.
In github-enterprise, administrator has not permission to show private repository, but has permission to `unlock` (temporarily gained full access to) with log reasen [![Gyazo](http://i.gyazo.com/e7cda4eef69dd698d6dbffa2cc4e4ee1.png)](http://gyazo.com/e7cda4eef69dd698d6dbffa2cc4e4ee1)

**Comment by my-dev** [comment] 2015-03-30 10:22
Hi! Mr. Cheers Mark.

thanks your comments.
I see. but I think [ private repository ] means that only collaborators can access, don't you.

In Your use case, It's a useful.
But this is inconvenience in almost cases.

I think...It's no good in secure...

**Comment by mgeorge** [comment] 2015-03-30 10:39
GitBucket is designed for small groups - not enterprises.  If you don't 
trust your administrator then you have other problems.  This is true for 
any service.  Administrators are God.  They need to be so that can 
properly administer the service.  Administration includes things like 
exporting and backups - something that can't be done without complete 
access.

Also remember that you don't actually have to use the administrator 
account.  I have an unprivileged account on most of our GitBucket 
instances for day-to-day operations, but have the ability to use the 
administrator account when I need it.

Sorry for arguing over this, but I have noticed a lot of scope creep 
happening on the mailing list lately.  The reason we love GitBucket is 
that it is lightweight and simple.  It doesn't need GitHub 
feature-parity or enterprise-level user management.  If you want that 
then use GitLab.


Cheers,
Mark

**Comment by my-dev** [comment] 2015-03-30 11:08
Hi! mr. mgeorge.

Sorry, I can't agree...
[ private repository ] means that only collaborators OR owner can access, don't you???
What Mr. nazoking say maybe have a point.

Administrators are GOD???
no!no!no!

It's only under collabrators... But In Other groups, No GOD!

[ GitBucket is designed for small groups ] you say.
but multi groups should be able to exists in secure, i guess.
multi administrators can exists per groups.

I think...

GitLab no thanks.f^^;

**Comment by takezoe** [comment] 2016-09-03 12:12
Merged with #1286

**Closed by takezoe** 2016-09-03 12:12 UTC
