### ISSUE TITLE
Importing repositories from other sites 

### ISSUE THREAD

**Issue by lavvy** [gitbucket/gitbucket#1780] opened 2017-11-20 23:30 UTC
Hello this wonderful piece of software needs this feature.  Infact i had doubted myself that it's not there until i confirmed that it is yet to be there. 
In this age of opensource many people prefer to import codes on the fly and start corroborating on the go. 
Some people don't have trusted hardwares they can pull source down to before pushing , so they prefer coding only on the web editor. 
And infact i think it's one the biggest reasons of having a git web frontend. 
I don't think it will be so hard to achieve, i think it  only takes a little knowledge of scala

**Comment by aadrian** [comment] 2017-11-21 00:02
duplicate of #255

**Closed by aadrian** 2017-11-21 00:02 UTC
