### ISSUE TITLE
Jenkins Github Organization job type not discovering Jenkinsfile in `master`

### ISSUE THREAD

**Issue by dkowis** [gitbucket/gitbucket#1946] opened 2018-04-09 02:45 UTC
## Issue
**Impacted version**: 4.23.0
* jenkins: 2.107.1
* github-branch-source: 2.3.3
* github-api: 1.90

**Deployment mode**: Standalone war file

**Problem description**:

I'm pretty confident this used to work, but I haven't been able to play with my jenkins/gitbucket setup at home in a while. The problem I'm seeing is that jenkins is no longer picking up the master branch to do builds on. It's not selecting the branch to do work.

```text
Organization URL: https://gitbucket.light.kow.is/dkowis
[Sun Apr 08 21:33:23 CDT 2018] Consulting GitHub Organization
21:33:23 Connecting to https://gitbucket.light.kow.is/api/v3 using dkowis/****** (David Kowis' Credentials)
21:33:23 Looking up repositories of myself dkowis
Proposing monopolytracker
Examining dkowis/monopolytracker

  Checking branches...

  Getting remote branches...

    Checking branch master

  Getting remote pull requests...
      ‘Jenkinsfile’ not found
    Does not meet criteria

  1 branches were processed

  Checking pull-requests...

  0 pull requests were processed

Finished examining dkowis/monopolytracker
```

There's only one branch, and it's got a `Jenkinsfile`, so it should be selected to build, but it appears that it's somehow unable to find that Jenkinsfile, and so is not building anything at all.

It will pick up pull requests, and other branches and build those, but it doesn't seem to do it until after the scan happens. I'm not sure if the pull request payload changed, but I don't think that's it. There's no errors in the log from Jenkins.

```text
INFO: dkowis_organization #20180408.212946 organization scan action completed: SUCCESS in 1.4 sec
Apr 08, 2018 9:30:22 PM org.jenkinsci.plugins.github.webhook.WebhookManager$1 run
INFO: GitHub webhooks activated for job dkowis_organization with [] (events: [REPOSITORY])
Apr 08, 2018 9:30:22 PM org.jenkinsci.plugins.github_branch_source.GitHubOrgWebHook register
WARNING: Failed to register GitHub Org hook to https://gitbucket.light.kow.is/dkowis (missing permissions?): {"message":"Not Found"}
Apr 08, 2018 9:30:30 PM jenkins.branch.OrganizationFolder$OrganizationScan run
INFO: dkowis_organization #20180408.213022 organization scan action completed: SUCCESS in 7.8 sec
```

**Comment by dkowis** [comment] 2018-04-09 02:49
Also of note, deleting and creating a new organization from scratch, and it picks up no branches to do work in.

**Comment by takezoe** [comment] 2018-04-09 05:53
I guess it caused by the bug in Contents API (#1943). It has been already fixed in #1940 and going to be released in tye next version of GitBucket (4.24.0 or 4.23.1).

**Comment by takezoe** [comment] 2018-04-09 10:13
Since this bug affects a lot of users, I will make a maintenance release 4.23.1 as soon as possible.

**Closed** 2018-04-09 17:40 UTC
Labels: duplicate

**Comment by takezoe** [comment] 2018-04-09 17:41
GitBucket 4.23.1 is out!
https://github.com/gitbucket/gitbucket/releases/tag/4.23.1

**Comment by tom-fv** [comment] 2018-12-18 11:22
This issue seems to have resurfaced again when I upgraded from 4.28 to 4.30, it used to find the jenkinsfile on all my branches when using the GitHub Multi-branch pipeline in Jenkins, now it doesn't find it on any giving the following message: 

```  Checking branches...

  Getting remote branches...

    Checking branch master
      ‘Jenkinsfile’ not found
    Does not meet criteria

    Checking branch develop
      ‘Jenkinsfile’ not found
    Does not meet criteria
```
There doesn't seem to be any errors on Jenkins or in the logs from GitBucket. This issue has made all my Jenkins multi branch git hub projects think that the branches no longer need to be built so nothing with build when using this method anymore (as it can't find any Jenkinsfile to build off). My guess is somewhere in the Gitbucket GitHub API it's not returning the files correctly, but thats as far as my knowledge goes XD
