### ISSUE TITLE
Unhandled error with the create repository API

### ISSUE THREAD

**Issue by Crayon2000** [gitbucket/gitbucket#2030] opened 2018-05-24 05:34 UTC
## Issue
**Impacted version**: 4.24.1

**Deployment mode**: 
* OS: Windows Server 2012 R2
* Server: IIS with URL Rewrite
* Service: NSSM to run GitBucket as a service
* Database: MariaDB 10.2.14

**Problem description**:
* When using the request (POST 127.0.0.1:8080/api/v3/user/repos) I get an unhandled error
* The body is `{"name":"test2"}`
* The repository is created but I get an 500 Server Error with this response: `{"message":"Internal Server Error"}`
* Using GET with the same URL is working
* Using POST with the same request a second time is working: `{"message":"A repository with this name already exists on this account","documentation_url":"https://developer.github.com/v3/repos/#create"}`
* I have tested the same request on another PC running GitBucket as a standalone app with the embedded H2 database and it's working 😕 
* Log: [gitbucket.log](https://github.com/gitbucket/gitbucket/files/2033913/gitbucket.log)

Let me know if you need more information.

**Comment by takezoe** [comment] 2018-05-27 14:14
It's caused by the difference of transaction isolation level of each database. The current create repository API  implementation expects READ COMMITTED but REPEATABLE READ is default in MariaDB (and MySQL too). We should fix our code to not depend on the isolation level.

**Closed** 2018-05-27 15:48 UTC
Labels: APIv3, bug

**Comment by Crayon2000** [comment] 2018-05-29 04:19
I have just tested GitBucket version 4.25.0 and it's working perfectly.

Thank you @takezoe :smile:

**Comment by takezoe** [comment] 2018-05-29 06:35
@Crayon2000 You're welcome! 💪
