### ISSUE TITLE
Release 4.34.0 erased group members

### ISSUE THREAD

**Issue by shhshn** [gitbucket/gitbucket#2541] opened 2020-08-31 23:25 UTC
# Issue
**Impacted version**: 4.34.0

**Deployment mode**: tomcat with nginx

**Problem description**:
- updating from 4.32.0 to 4.34.0 resulted in empty groups (e.g. no members assigned to any group)
    - all the groups just looked like empty, if I remember correctly (forgot to take a screenshot ...)
    - after that, adding a new member to an existing group made a pop up like "at least one should be a manager"
- simply rolling back to 4.32.0 with backup DB mitigate the problem
    - I haven't tested 4.33.0, but I do suspect "enhancement admin settings UI" in 4.34.0 might be related
    - I love GitBucket so I can stick more with 4.32.0 ☺️ 

**How to reproduce**:
- create at least one group with one member using 4.32.0
- and then update the GitBucket package to 4.34.0
- open admin option and show list of groups
    - (optional) try adding a new member to the group

**Comment by shhshn** [comment] 2020-11-18 23:45
Status update for @takezoe.

I have tried a bit more smooth migration from 4.32.0 to 4.33.0 and then 4.34.0, but failed within the same condition (erased group members).
Everything seemed quite normal, until I/admin have actually performed "sign out" 🤔 

Tomorrow I will investigate more and will update again.

**Comment by shhshn** [comment] 2020-11-19 23:54
Status update: please find the attached screenshots 📷
Now I am sure that **4.34.0 is the only impacted version**.

There are _two issues_ to be more precise:
1. update from 4.33.0 to 4.34.0 erased commit messages
     - you can immediately find diff after the update (see Fig A and B)
2. update from 4.33.0 to 4.34.0 erased group members
     - you may need to sign out, clean cache/cookie, and then sign in (see Fig C and D)

Screenshots:
- Fig. A<img width="200" alt="Screen Shot 2020-11-20 at 7 36 16" src="https://user-images.githubusercontent.com/15028546/99738144-2cbbb380-2b0d-11eb-8f53-b77226b79432.png">
- Fig. B: <img width="200" alt="Screen Shot 2020-11-20 at 7 38 19" src="https://user-images.githubusercontent.com/15028546/99738154-2fb6a400-2b0d-11eb-919d-ba3b243efae9.png">
- Fig. C: <img width="200" alt="Screen Shot 2020-11-20 at 7 36 29" src="https://user-images.githubusercontent.com/15028546/99738153-2f1e0d80-2b0d-11eb-9630-fcadfd62bf80.png">
- Fig. D: <img width="200" alt="Screen Shot 2020-11-20 at 7 42 01" src="https://user-images.githubusercontent.com/15028546/99738155-304f3a80-2b0d-11eb-87c2-bfc588161667.png">

**Comment by takezoe** [comment] 2020-11-20 00:38
> update from 4.33.0 to 4.34.0 erased commit messages 

This is an intentional change by https://github.com/gitbucket/gitbucket/pull/2468, at least.

**Comment by takezoe** [comment] 2020-11-20 00:50
> update from 4.33.0 to 4.34.0 erased group members 

4.34.0 doesn't include any update related the group management. Could you check HTML and whether the following element is generated at the place where user's icons should be displayed?

```html
<img src="/test/_avatar?20201120094503" class="avatar-mini" style="width: 20px; height: 20px;" data-toggle="tooltip" title="" alt="@test" data-original-title="test">
```

If HTML is generated but icons are not displayed, maybe GitBucket is failing to generate icons. You might be able to find something in GitBucket logs.

**Comment by shhshn** [comment] 2020-11-20 06:10
Thank you for the detailed comments!
I have taken a snapshot of the server for further investigation.

> This is an intentional change by #2468, at least.

Oops, edited my message ✏️ 

> Could you check HTML of the page and whether the following element is generated at the place where user's icons should be displayed?

It seems nothing but group icons had been generated.
```html
        <tr>
          <td >
            <div class="pull-right">

                <a href="/gitbucket/admin/users/my-repo-name-here/_editgroup">Edit</a>

            </div>
            <div class="strong">
              <a href="/gitbucket/my-repo-name-here" class=""><img src="https://www.gravatar.com/avatar/a2ffb5771efe24194bf57854033207ce?s=20&d=retro&r=g" class="avatar-mini" style="width: 20px; height: 20px;" /></a>
              <a href="/gitbucket/my-repo-name-here">my-repo-name-here</a>

                (Group)




            </div>
            <div>
              <hr>


            </div>
            <div>
              <span class="muted">Registered:</span> 2016-04-26 09:35:26
              <span class="muted">Updated:</span> 2016-04-26 09:35:26

            </div>
          </td>
        </tr>
```


In addition, no member has been assigned to the group when you "Edit" it.

However, the DB looks like normal, as
```sql
SELECT * FROM GROUP_MEMBER
```
worked as intended (listed all the combination of groups and members).

Hope this helps 🙏

**Comment by takezoe** [comment] 2020-11-29 04:42
Hmm. That's weird... Does that happen with the clean installation too?

**Comment by shhshn** [comment] 2020-12-28 08:52
@takezoe sorry for replying literary very late 🙏 

I have just tried a clean installation yet no luck so far.
Turned out the following was not the reproduce procedure:
- install GitBucket 4.32.0
- login as the default user (root)
- create a new account (test)
- create a new group (group) where the new account as manager
- install GitBucket 4.34.0
- login as the default user, logout, and login

Also found that the latest version could not startup using our old DB.
I don't know what to do ¯\_(ツ)_/¯

**Comment by takezoe** [comment] 2020-12-28 14:37
> Also found that the latest version could not startup using our old DB.

The latest version has a database migration issue (https://github.com/gitbucket/gitbucket/pull/2610) so I'm now preparing 4.35.1 which is a hotfix release.

**Comment by shhshn** [comment] 2021-02-17 02:37
@takezoe Good news, installing 4.35.3 resolved my issue!
It's already up and running for one day with no problem. So we can close the case now.
Thank you very much for helping me with several investigations:pray:

Summary: we can skip 4.34.0 and instead use the latest build as a workaround.
So far I could not figure out what was the exact cause, or make a minimum repro steps.
I think there's something behind `git diff 4.34.0 4.35.3` but it's maybe not worth a try.

**Comment by takezoe** [comment] 2021-02-17 03:23
That's good to hear. I'm also not sure why 4.34.0 didn't work and why 4.35.3 worked. 🤔 Anyway, I wouldn't spend time on further investigation since you confirmed that the latest version works without this issue. Let's just close this issue.

**Closed** 2021-02-17 03:23 UTC
