### ISSUE TITLE
generic ssh user

### ISSUE THREAD

**Issue by semudu** [gitbucket/gitbucket#971] opened 2015-11-06 11:30 UTC
ssh urls are generated by the user name but I think, if we use a generic user for ssh (ex: git@gitbucket.machine.com), it would be better.

**Comment by nus** [comment] 2015-11-06 13:50
+1

**Comment by nazoking** [comment] 2015-11-07 08:55
+1

But this feature spec has some issues.

 - If some users already set same ssh-key to your gitbucket ?
   - raise exception on upgrade?
 - Can users login by current userid ?
   - If user `git` already exists ?

**Comment by tette** [comment] 2015-11-07 12:12
+1

In consideration of the integrity, I think this feature should be enabled in the options.

**Comment by semudu** [comment] 2015-11-07 15:07
i think, ssh-key is a special key for a user so same ssh-key is an extreme case. Of course, users can login by their userid but ssh clone url can be generated for one generic system user like "git". In this way, we don't have to create a system user on the host os for every user to login via ssh.

**Comment by ritschwumm** [comment] 2016-01-21 03:47
i want this. what's missing in @P1tt187 branch mentioned above?

**Comment by ritschwumm** [comment] 2016-01-21 14:39
just for the record: https://github.com/P1tt187/gitbucket/commit/4a02a880dfa3c31c7eb0edb509bfd01832981f62 does allow pulling, but not pushing. i think i know how to get that working, too.

**Comment by ritschwumm** [comment] 2016-01-22 01:05
i seem to have got git push working. now, what else is needed?
* instead of scanning all ssh keys manually, a findByKey should be used
* two accounts with different user names but the same ssh key cannot push at all at the moment
* an existing user named "git" should still be able to work
* how about legacy urls including the user name? i'd prefer getting rid of them in a clean sweep.

**Comment by ritschwumm** [comment] 2016-01-26 21:40
making this configurable in a proper way turns out to be slightly messy, see  #734

**Comment by ritschwumm** [comment] 2016-01-30 11:06
got it. as soon as #1084 is merged, i'll  open a pull request.

**Closed** 2016-05-14 10:26 UTC
Labels: improvement

**Comment by bviktor** [comment] 2017-01-17 16:37
How does authentication work in this case? It's not quite clear to me and I can't find related documentation. Does username become "git" for EVERY user, then upon push/pull GitBucket searches for ALL user's SSH keys and if there's ANY match it authenticates?

**Comment by ritschwumm** [comment] 2017-01-17 18:28
almost. if the ssh username is "git" then ALL user's ssh keys are searched, and if there's EXACTLY ONE found, the user having that key is authenticated. if there's more than one matching key, authentication fails. if the username is anything else, only that user's key is used for authentication.

**Comment by bviktor** [comment] 2017-01-17 19:06
So the only reason I've found in this ticket for this weird behavior is being able to omit the username from the URL. Correct?

1) Why is it a problem if we have a username in the remote URL? That's not really clear to me. This is a pretty big change without clear motivation or explanation. For automated things you use helper users like "jenkins" or whatever, I don't see how it's less "annoying" to put "jenkins" in a Maven config instead of "git".

2) If it's not about automated things but your own workstation instead, then why don't you use the HTTP URL without username and a Git credential helper which take care of authentication for you and you don't have to type your username and password ever again? Instead of having a "wildcard" user which matches for anything?

3) But let's say there's a legit use case for this. Why do we assume here that everyone wants to omit usernames from the SSH URL? Especially when it's a performance hit? At least make this optional please.

4) If the original goal was to **avoid** usernames, then why do we use a randomly picked username instead? Clone only works if I **do** insert git@ in the URL. If I omit username, all I get is:

~~~
fatal: protocol error: bad line length character: logi
~~~

5) GitBucket also generates the URL with the git@ part added when I select SSH transport.

You could say "just use the actual username in the remote then", yes, but that requires manual intervention - something that's defective by design coz you simply can't expect users to take care of this properly all the time.

So this change basically lacks an explanation for its existence, doesn't achieve its goal, degrades performance and makes it mandatory for everyone. Uhh...

**Comment by bviktor** [comment] 2017-01-17 19:30
Anyway, wasn't trying to sound offensive, I hope none taken. I can't expect to have any code change just because I disagree, but I think at least documenting the behavior that you just explained sure would help. Shall I create an article in the Wiki? I saw there's a link already for SSH auth, but it's not done yet.

**Comment by ritschwumm** [comment] 2017-01-19 08:55
1) i found it quite annoying to communicate the details of git access in a team were people joined and left on a regular basis. a significant fraction got it wrong first, so i had to come to their desk to help. always having the same user stopped them from interrupting me while i was working ;)

2) who would want http? it's not even encrypted...

3) it _is_ optional. you can still use your own user name without taking a performance hit.

4) it's not exactly picked randomly. gitbucket reserves urls starting with /git for its own purposes and therefore disallows a gitbucket user being "git", so that was the one name that was guaranteed not to lead to clashes with existing names. which i wanted to stay backwards-compatible for users using the older username@ urls.

**Comment by bviktor** [comment] 2017-01-19 12:17
Thanks for your response. One last thing I'd like to point out is that HTTP of course _is_ encrypted with TLS. In fact, our root domain is on HSTS preload so we couldn't have plain HTTP even if we wanted to :)

In fact, I find HTTP much less cumbersome. You have to to have the HTTP ports open for the web UI, you have to have an HTTP user and password for account management. So HTTP is a given and SSH is basically just more ports and more credentials to fiddle with on top of the necessary HTTP. To each their own though.

Either way, I still think an admin option would be nice to offer the user.name@ remote _by default_ instead of git@. Just my opinion.
