### ISSUE TITLE
IOException caused by repository deletion

### ISSUE THREAD

**Issue by YoshinoriHonma** [gitbucket/gitbucket#544] opened 2014-11-07 00:55 UTC
1. リポジトリ作成
2. ローカルにclone
3. 編集してpush
4. リポジトリ削除

1度もpushしていないリポジトリは削除できるようです
リポジトリの削除はSettingsのDanger Zoneからリポジトリを削除です

編集についてはver2.5ではReadMe.mdをGitBucket上で編集した場合は問題なく削除できます
2.5以外のバージョンについてはGitBucket上での編集については確認していません

発生バージョン：2.3、2.4、2.4.1、2.5
※ 2.3より以前は確認してません

**Comment by pcqpcq** [comment] 2015-04-27 10:48
+1 for this.
btw, could we discuss in english?

**Comment by takezoe** [comment] 2015-04-27 17:28
> could we discuss in english?

@pcqpcq Yes, of course. I expect other users have locked repository files by git operation when you tried to delete repository. Maybe GitBucket should retry some times if failed to delete repository.

**Comment by ChaseFlorell** [comment] 2015-07-13 13:49
This is the same issue as #745.  I do not think that a retry will be successful because the java process is what's locking the file (I presume that the original error report was for Windows). 
What needs to happen is that the Java process needs to release the .pack file.

**Comment by McFoggy** [comment] 2016-04-01 10:13
check that we do not face one of the non closed  resources described in [JGIT 448570](https://bugs.eclipse.org/bugs/show_bug.cgi?id=448570)

**Comment by msakuta** [comment] 2016-05-17 04:33
Same happened here, with

* GitBucket 4.0
* Windows 7 64bit
* Started with `java -jar gitbucket.war`

No matter how many times you retry deleting, this issue persists.
But stopping and restarting the process resolved the issue.

Git on Windows tend to be problematic. I saw the same issue (can't delete a pack file because someone keeps it open) with multiple Git clients installed. Probably JGit have the same issue.

**Comment by kounoike** [comment] 2018-01-16 12:32
On Windows, the file can't delete when it opened by any process. In this case, JGit doesn't closed such .pack file. By this Issue and #1842 indicates `git push` action is one of the triggers which doesn't close .pack file. I can easily reproduce this problem.

I checked this problem with [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer). I tried:

- (precondition) create root/test repository
- (precondition) prepare local work copy with one commit.
-  (reproduce step) push it to GitBucket server.

After this step, the file `C:\Users\kounoike\.gitbucket\repositories\root\test.git\objects\pack\pack-9c65033457a61e414ca4007a8ae808e019d89e8b.pack` doesn't closed.

![20180116-212328](https://user-images.githubusercontent.com/6997928/34988892-b5e0d5a6-fb03-11e7-995b-f2b6467dc0bd.png)

It's maybe JGit's issue. But I can't create issue because I can't explain this problem without GitBucket usage.

**Comment by McFoggy** [comment] 2018-01-16 12:50
unless it is a real jgit issue, we might still have some piece of code that does not close correctly jgit resources.

**Comment by kounoike** [comment] 2018-01-16 12:59
@takezoe do you know small example which uses JGit GitSErvlet? I think it occurs same issue.

hmm.. this issue is more serious. On my windows 7/GitBucket 4.20.0, one File pointer leaks by **every** push.

In this case:

- push root/test
- push root/test2
- push root/test
- push root/test.

by these steps, GitBucket leaks 3 root/test file and 1 root/test2 file.

![20180116-214824](https://user-images.githubusercontent.com/6997928/34990116-3c48d374-fb08-11e7-9b3c-6c8156c04b73.png)

**Comment by kounoike** [comment] 2018-01-16 15:44
I wrote reproducing steps without GitBucket. just use Tomcat/JGit. But it wrote in Japanese. sorry.

https://gist.github.com/kounoike/075351e77ea0a8a71e66d8ee47ddf606

**Comment by takezoe** [comment] 2018-01-16 15:59
@kounoike Thanks for your investigation! We got a lot of clues.

**Comment by akiotakahashi** [comment] 2018-01-17 03:39
From my investigation, the cause is a cached repository object. We need special procedures on the caller side to delete pack files.

1. JGit RepositoryCache holds a reference to a instance of FileRepository and it holds a ObjectDirectory object having open RandomAccessFile objects indirectly preventing the directory from deleteting.
2. So we need to close the ObjectDirectory object in the cached FileRepository object before deletion.
3. But an cached Repository object is NOT closed actually when its reference-counter is decremented to zero. (see implementation of Repository.close)
4. Thus we need special steps before delete pack files such as  JGit GC.deleteOldPacks calls close method manually.

My investigation is done by using jcmd (heap_dump) targettng a standalone GitBucket instance and jhat.

Execuse me that no solutions are proposed here. Thanks.

**Comment by kounoike** [comment] 2018-01-17 15:39
I found more file leak case...

repo GC leaks \path\to\.gitbucket\root\test.git\pack directory handle...

**Comment by joshuacurtiss** [comment] 2018-05-21 17:43
This happens often for us when transferring/deleting repos. In fact, to the point that I wouldn't want to do a delete/move in front of my boss and he see system error.  What do you think about keeping a queue, perhaps even in GB database, of needed deletions.  If they fail, they can be retried on restart or after XX time. Just throwing out ideas.

**Comment by takezoe** [comment] 2018-05-22 10:10
@joshuacurtiss 

>  In fact, to the point that I wouldn't want to do a delete/move in front of my boss and he see system error.

Completely understandable!

I've never seen repository deletion error in Mac and Linux, but it often reported by Windiws users. I think it makes sense to queue and do repository deletion in background (of course, it will be retried when it fails) to prevent this trouble.

**Closed** 2019-01-20 08:07 UTC
Labels: bug
