### ISSUE TITLE
Login page redirect issue

### ISSUE THREAD

**Issue by dbronecki** [gitbucket/gitbucket#1567] opened 2017-05-01 17:29 UTC
## Issue
**Impacted version**: 4.12

**Deployment mode**:  linux, nginx

**Problem description**:
I'm using Gitbucket deployed in nginx under subpath (for example: `mydomain.com/gitbucket/`) without anonymous access. This URL is configured in System settings page.

In 4.12 redirect to login page is not working correctly - it redirects to `mydomain.com/signin` instead of `mydomain.com/gitbucket/signin`. In 4.11 it was working just fine.

I looked into git history and this issue is caused by this commit https://github.com/gitbucket/gitbucket/commit/956af54d4f9aec4d03341412670807619d42665a - when I revert changes in this commit everything works as expected.

**Comment by juanfcocontreras** [comment] 2017-05-01 19:56
The same here with Apache. The problem is that now I can't run previous version:

`java.lang.IllegalStateException: Initialization failed. GitBucket version is 4.11.0, but database version is 4.12.0`

**Comment by dbronecki** [comment] 2017-05-01 20:02
If you have access to database, just run SQL 
```sql
UPDATE versions
   SET version='4.11.0'
 WHERE module_id='gitbucket-core';
```
then you will be able to run old version.

**Comment by juanfcocontreras** [comment] 2017-05-01 20:06
@dbronecki, how can I connect to gitbucket database?

**Comment by dbronecki** [comment] 2017-05-01 20:12
Well it depends which database you are using. I use PostgreSQL and using PgAdmin to connect. But if you did not changed any database configuration, you should have file `data.mv` under `~/.gitbucket` directory. You should use H2 console to connect with this database.

**Comment by dbronecki** [comment] 2017-05-01 20:20
@juanfcocontreras I made pull request with fix, hopefully @takezoe will merge it.

**Comment by juanfcocontreras** [comment] 2017-05-01 20:22
@dbronecki, thanks so much, could you link a full .war with the patch included?

**Comment by dbronecki** [comment] 2017-05-01 20:44
You can build one by yourself - just clone my fork of gitbucket:
`https://github.com/dbronecki/gitbucket.git`
then checkout branch with fix:
`git checkout issue/1567`
then run:
`sbt executable`

After this .war file will be build under path `target/executable/gitbucket.war`.

**Comment by juanfcocontreras** [comment] 2017-05-01 21:08
@dbronecki, everything went well. I don't know anything about Scala. Thank you so much!

I hope this issue will be fixed shortly.

**Closed** 2017-05-02 03:40 UTC
Labels: bug
