### ISSUE TITLE
push event webhook payload inconsistent with GitHub

### ISSUE THREAD

**Issue by aecspades** [gitbucket/gitbucket#3096] opened 2022-07-26 17:06 UTC
## Issue
**Impacted version**: 4.37.1

**Deployment mode**: standalone app

**Problem description**:
The `push` event webhook payload returned by GitBucket is inconsistent with the GitHub standard defined [here](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push).

1. Specifically, for the `ref` property/key the GitHub documentation says "The full [git ref](https://docs.github.com/en/rest/reference/git#refs) that was pushed".

GitBucket **is** correctly returning the full ref in the payload when the branch is created from the GitBucket's web interface e.g. `"ref": "refs/heads/feature/Feature-0" `

GitBucket **is not** correctly returning the full ref in the payload when the branch is created from a push/publish from a client e.g. `"ref": "feature/Feature-0"` i.e. the `"refs/heads/"` prefix is missing.

  2. For the `ssh_url` key/property, the webhook is returning e.g. `ssh://git@10.3.40.102:7022/ACLARK/arcad-example2.git:ACLARK/arcad-example2.git` instead of the "clone" URL `ssh://git@10.3.40.102:7022/ACLARK/arcad-example2.git` i.e. GitBucket is appending `":USER_NAME/PROJECT_NAME.git"` to the name that GitHub returns.  

This issue (issue 2 here, **not** issue 1 above) may be the same/related to bug #2293?

**Comment by edmundreinhardt** [comment] 2022-07-26 18:28
Also very interested in the resolution to this problem.

**Comment by takezoe** [comment] 2022-09-03 03:17
> GitBucket is correctly returning the full ref in the payload when the branch is created from the GitBucket's web interface e.g. "ref": "refs/heads/feature/Feature-0"
>
> GitBucket is not correctly returning the full ref in the payload when the branch is created from a push/publish from a client e.g. "ref": "feature/Feature-0" i.e. the "refs/heads/" prefix is missing.

Hmm, I cannot reproduce this issue on my laptop. I created a branch on my local repo and pushed it to GitBucket but `ref` had `refs/heads/` prefix.

**Comment by takezoe** [comment] 2022-09-03 03:22
Ah, maybe it's a create web hook, not a push webhook?

**Comment by takezoe** [comment] 2022-09-03 04:07
Both issue 1 and issue 2 will be fixed in https://github.com/gitbucket/gitbucket/pull/3122

**Closed** 2022-09-03 04:15 UTC
Labels: bug
