### ISSUE TITLE
push event webhook payload inconsistent with GitHub

### ISSUE THREAD

**Issue by aecspades** [gitbucket/gitbucket#3638] opened 2024-11-04 15:31 UTC
## Issue
**Impacted version**: 4.41.0

**Deployment mode**: standalone app

**Problem description**:
This appears to be the exact same problem as #3096 which was fixed by @takezoe 2 years ago, but the problem seems to have
 re-appeared.

The `push `event webhook payload returned by GitBucket is inconsistent with the GitHub standard defined [here](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push).

Specifically, for the `ref `property/key the GitHub documentation says "The full [git ref](https://docs.github.com/en/rest/reference/git#refs) that was pushed".
GitBucket is correctly returning the full ref in the payload when the branch is created from the GitBucket's web interface e.g. `"ref": "refs/heads/feature/Feature-0" `

GitBucket is **not** correctly returning the full ref in the payload when the branch is created from a push/publish from a client e.g. `"ref": "feature/Feature-0"` i.e. the `"refs/heads/"` prefix is missing.

The complete payload is included in the attached log from our webhook handler:
[scmEvent_11_Logs9180512848645971038.log](https://github.com/user-attachments/files/17620322/scmEvent_11_Logs9180512848645971038.log)

**Comment by JinhuaXie** [comment] 2024-11-11 02:17
The fix was applied 2 years ago but not in RepositoryViewerController.scala; The incorrect ref value was from it.
<img width="403" alt="image" src="https://github.com/user-attachments/assets/32b8f7e2-dc74-4872-967f-e6969c8486f5">

Also, the SSH_URL was incorrect in the webhook payload. Only having the server url but missing the path of the repository:
URLs:
	http://10.5.11.101:8082/arcad/ademo
	git@10.5.11.101:8022

**Comment by takezoe** [comment] 2024-12-08 16:34
@aecspades Still I can't reproduce the problem. Could you provide a minimum step-by-step procedure for reproduction?

**Comment by takezoe** [comment] 2024-12-08 17:19
@JinhuaXie Thank you for sharing. #3656 will also fix `ssh_url`.

**Comment by aecspades** [comment] 2024-12-09 14:48
Hi @takezoe the problem only seems to happen when the repository is created in a group - when it is directly created under a profile, it seems to work fine - @JinhuaXie please correct me if I'm wrong or please add additional details.

**Comment by JinhuaXie** [comment] 2024-12-10 06:57
hi @takezoe @aecspades yes, the incorrect ref and ssh_url in the Webhook payloads only triggered from the operation in Web UI. If the commit pushed from local to the remote Gitbucket repository, the ssh_url and the ref will be correct in the webhook payloads. 

@takezoe the fix in #3656 might not fix the ssh_url issue. Seems it will miss the 'SSH://' prefix if the port is not 22.
**before this fix:** 
correct ssh_url --> 'ssh_url': 'ssh://git@127.0.0.1:8022/arcad/ademo.git'
incorrect ssh_url from web operation --> 'ssh_url': 'git@127.0.0.1:8022'
**after apply the fix:**
 'ssh_url': 'git@127.0.0.1:8022/arcad/ademo.git'

Regarding issue that the repository created in a group or under a profile, it is something related to the permission. The scenario is:
1. I have a user in Gitbucket and register my ssh key into this user;
2. I created a new group and add the user as manager;
3. I created the repository under the group;
4. I was able to make git operations clone, commit, push to that repository without any permission issue;
5. But again on Webhook payloads to trigger some operation with jgit api, it failed with exception that the remote not available to fetch (with the same ssh key)
6. I have no clue where the problem comes from. It is possible related to owner in the payloads, it indicates the group as a login, type Organization.

**Comment by takezoe** [comment] 2024-12-14 05:55
> 'ssh_url': 'git@127.0.0.1:8022/arcad/ademo.git'

Thanks. Applied additional fix (https://github.com/gitbucket/gitbucket/pull/3656/commits/20daca3d8b86676cc4b42d166305561e0fcf0476) though this might have unexpected negative impact on somewhere 🤔

**Comment by takezoe** [comment] 2024-12-14 05:58
> I have no clue where the problem comes from. It is possible related to owner in the payloads, it indicates the group as a login, type Organization.

Ah, I see. That sounds a bit more complicated issue than WebHook payload issue.

**Comment by takezoe** [comment] 2024-12-19 06:21
Merged #3656 it fixes ref and ssh_url but doesn't fix the group repository issue. I haven't confirmed that issue myself yet.

**Comment by takezoe** [comment] 2024-12-22 23:55
I think the schema of payload is now compatible with GitHub thanks to #3656. Can we close this issue and create new one for the group repository issue?

**Comment by JinhuaXie** [comment] 2024-12-23 03:53
Thank you. I think it would be good.

**Closed** 2024-12-24 02:13 UTC
Labels: bug, APIv3
